// Authentication
export const AUTHENTICATION_START = "AUTHENTICATION_START";
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS";
export const AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR";
export const AUTHENTICATION_LOGOUT = "AUTHENTICATION_LOGOUT";

// Spotify Connection
export const SPOTIFY_CONNECT_SUCCESS = "SPOTIFY_CONNECT_SUCCESS";
export const SPOTIFY_CONNECT_ERROR = "SPOTIFY_CONNECT_ERROR";

// User data
export const USER_DATA_START = "USER_DATA_START";
export const USER_DATA_SUCCESS = "USER_DATA_START_SUCCESS";
export const USER_DATA_ERROR = "USER_DATA_START_ERROR";


