// Authentication
export const AUTHENTICATION_START = "AUTHENTICATION_START";
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS";
export const AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR";
export const AUTHENTICATION_LOGOUT = "AUTHENTICATION_LOGOUT";

// Spotify Connection
export const SPOTIFY_CONNECT_SUCCESS = "SPOTIFY_CONNECT_SUCCESS";
export const SPOTIFY_CONNECT_ERROR = "SPOTIFY_CONNECT_ERROR";

// User data
export const GET_USER_DATA_START = "USER_DATA_START";
export const GET_USER_DATA_SUCCESS = "USER_DATA_START_SUCCESS";
export const GET_USER_DATA_ERROR = "USER_DATA_START_ERROR";
export const UPDATE_USER_ROOMS = "UPDATE_USER_ROOMS";

// Room Actions
export const GET_USER_ROOMS_SUCCESS = "GET_USER_ROOMS_SUCCESS";
export const GET_USER_ROOMS_ERROR = "GET_USER_ROOMS_ERROR";

export const GET_SHARED_ROOMS_SUCCESS = "GET_SHARED_ROOMS_SUCCESS";
export const GET_SHARED_ROOMS_ERROR = "GET_SHARED_ROOMS_ERROR";

export const DELETE_ROOM_SUCCESS = "DELETE_ROOM_SUCCESS";
export const DELETE_ROOM_ERROR = "DELETE_ROOM_ERROR";

export const UNSUBSCRIBE_ROOM = "UNSUBSCRIBE_ROOM";

export const CREATE_ROOM_SUCCESS = "CREATE_ROOM_SUCCESS";
export const CREATE_ROOM_ERROR = "CREATE_ROOM_ERROR";

export const GET_ROOM = "GET_ROOM";
export const JOIN_ROOM = "JOIN_ROOM";

// Playlist Actions
export const SEARCH_SONG_START = "SEARCH_SONG_START";
export const SEARCH_SONG_SUCCESS = "SEARCH_SONG_SUCCESS";
export const SEARCH_SONG_ERROR = "SEARCH_SONG_ERROR";

export const GET_TRACK_SUCCESS = "GET_TRACK_SUCCESS";
export const GET_TRACK_ERROR = "GET_TRACK_ERROR";

export const GET_AVAILABLE_DEVICES = "GET_AVAILABLE_DEVICES";

export const PLAY_SONG_SUCCESS = "PLAY_SONG_SUCCESS";

export const ADD_NEW_SONG_TO_VOTING_LIST = "ADD_NEW_SONG_TO_VOTING_LIST";
export const UPDATE_VOTING_LIST = "UPDATE_VOTING_LIST";
